baseURL = 'https://kohut.xyz'
languageCode = 'sk'
title = 'Gabriel Kohut'

[params]
email = "gabriel@kohut.xyz"
firstName = "Gabriel"
lastName = "Kohut"

[[params.handles]]
    name = "Instagram"
    link = "https://instagram.com/stromokocur_5"
    icon = "instagram"
    
[[params.handles]]
    name = "Discord"
    link = "https://discord.com/users/939846623289290763"
    icon = "discord"

[[params.handles]]
    name = "X"
    link = "https://x.com/stromokocur5"
    icon = "x"

[[params.handles]]
    name = "Tiktok"
    link = "https://www.tiktok.com/@stromokocur5"
    icon = "tiktok"

[[params.handles]]
    name = "Github"
    link = "https://www.github.com/stromokocur5"
    icon = "github"

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '#about'
    weight = 1
  [[menus.main]]
    name = 'Skills'
    pageRef = '#skills'
    weight = 2
  [[menus.main]]
    name = 'Creations'
    pageRef = '#creations'
    weight = 3
  [[menus.main]]
    name = 'Experience'
    pageRef = '#experience'
    weight = 4
  [[menus.main]]
    name = 'Education'
    pageRef = '#education'
    weight = 5


