baseURL = 'https://kohut.xyz'
languageCode = 'sk'
title = 'Gabriel Kohut'

[params]
email = "gabriel@kohut.xyz"
firstName = "Gabriel"
lastName = "Kohut"

[[params.handles]]
    name = "Instagram"
    link = "https://instagram.com/stromokocur_5"
    icon = "instagram"
    
[[params.handles]]
    name = "Discord"
    link = "https://discord.com/users/939846623289290763"
    icon = "discord"

[[params.handles]]
    name = "X"
    link = "https://x.com/stromokocur5"
    icon = "x"

[[params.handles]]
    name = "Tiktok"
    link = "https://www.tiktok.com/@stromokocur5"
    icon = "tiktok"

[[params.handles]]
    name = "Github"
    link = "https://www.github.com/stromokocur5"
    icon = "github"

    
[[params.skills.architecture]]
    name = "API Management Platforms"
    icon = "terminal"

[[params.skills.architecture]]
    name = "DevOps"
    icon = "terminal"

[[params.skills.architecture]]
    name = "DNS"
    icon = "terminal"

[[params.skills.architecture]]
    name = "Firewalls"
    icon = "terminal"

[[params.skills.architecture]]
    name = "Microservices"
    icon = "terminal"

[[params.skills.architecture]]
    name = "REST"
    icon = "terminal"

[[params.skills.architecture]]
    name = "Webservices"
    icon = "terminal"

[[params.skills.languages]]
    name = "Rust"
    icon = "rust"

[[params.skills.languages]]
    name = "Go"
    icon = "go"

[[params.skills.languages]]
    name = "Typescript"
    icon = "typescript"

[[params.skills.languages]]
    name = "Git"
    icon = "git"

[[params.skills.languages]]
    name = "Shell"
    icon = "terminal"

[[params.skills.languages]]
    name = "Linux"
    icon = "linux"

[[params.skills.cloud]]
    name = "Docker"
    icon = "docker"

[[params.skills.cloud]]
    name = "AWS"
    icon = "aws"

[[params.skills.cloud]]
    name = "Nginx"
    icon = "nginx"

[[params.skills.cloud]]
    name = "Terraform"
    icon = "terminal"

[[params.skills.cloud]]
    name = "Cloudflare"
    icon = "cloudflare"


[[params.education]]
    name = "Stredná odborná škola techniky a služieb, Kollárova 17, Sečovce"
    field = "Information and Communication Technology"
    start = 2022
    end = 2026


[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '#about'
    weight = 1
  [[menus.main]]
    name = 'Skills'
    pageRef = '#skills'
    weight = 2
  [[menus.main]]
    name = 'Education'
    pageRef = '#education'
    weight = 3
  [[menus.main]]
    name = 'Creations'
    pageRef = '#creations'
    weight = 4
  [[menus.main]]
    name = 'Experience'
    pageRef = '#experience'
    weight = 5
